# .github/workflows/create-release.yml
name: Create Release

on:
  push:
    tags:
      - 'v*'  # Matches tags like v1.0.0, v2.5.3, etc.

permissions:
  contents: write  # Required to create GitHub Releases

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true

